# Generated by Django 5.2.1 on 2025-07-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipogasto_remove_doctor_duracion_cita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='ruc',
            field=models.CharField(help_text='Ingrese un RUC válido (persona natural, sociedad o extranjero).', max_length=13, unique=True, verbose_name='Ruc'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula_ecuatoriana',
            field=models.CharField(help_text='Ingrese el número de cédula sin espacios ni guiones.', max_length=10, verbose_name='Cédula'),
        ),
    ]
