# Generated by Django 5.2.1 on 2025-07-02 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_remove_atencion_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturacionMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la facturación.', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última fecha de modificación de la facturación.', verbose_name='Fecha de Actualización')),
                ('numero_factura', models.CharField(help_text='Número único de factura para identificación.', max_length=50, unique=True, verbose_name='Número de Factura')),
                ('observaciones_facturacion', models.TextField(blank=True, help_text='Notas adicionales sobre el proceso de facturación.', null=True, verbose_name='Observaciones de Facturación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('pago', models.OneToOneField(help_text='Pago principal al que pertenece esta facturación.', on_delete=django.db.models.deletion.CASCADE, related_name='facturacion', to='doctor.pago', verbose_name='Pago Principal')),
            ],
            options={
                'verbose_name': 'Facturación Médica',
                'verbose_name_plural': 'Facturaciones Médicas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
