# Generated by Django 5.2.1 on 2025-07-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_facturacionmedica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FacturacionMedica',
        ),
    ]
