# Generated by Django 5.2.1 on 2025-07-04 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_doctor_ruc_alter_paciente_cedula_ecuatoriana'),
        ('doctor', '0007_delete_facturacionmedica'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='cita',
            field=models.ForeignKey(blank=True, help_text='Cita médica que originó esta atención.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atencion', to='doctor.citamedica', verbose_name='Cita Médica'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='doctor',
            field=models.ForeignKey(default=1, help_text='Doctor que realiza la atención médica.', on_delete=django.db.models.deletion.PROTECT, related_name='atenciones', to='core.doctor', verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='citamedica',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.doctor', verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='core.doctor', verbose_name='Doctor'),
        ),
    ]
